### PR TITLE
feat: Add 3 new modules: add lifeblood, soul and activate fury on boss scene entry

### PR DESCRIPTION
**Pull request by TheMulhima**
you probably have to edit `zh,json` and add the new features into `README.zh.md`.

### CODE REVIEW

**Comment by Clazex** [comment]
Merged into a seperate branch first. Will do some further work before merging into main

**Comment by Clazex** [comment]
This repo uses [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard, and use [commitizen](https://github.com/commitizen/cz-cli#readme) to help ensure that, then use [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) to auto-generate changelogs. The `CHANGELOG.md` thing comes from [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).

**Comment by TheMulhima** [comment]
> This repo uses [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard, and use [commitizen](https://github.com/commitizen/cz-cli#readme) to help ensure that, then use [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) to auto-generate changelogs. The `CHANGELOG.md` idea comes from [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).

Sorry for messing up the format

**Comment by Clazex** [comment]
Sorry too for the still WIP `CONTRIBUTING.md`, I'll fix all the thing later.

**Pull request merged**
